import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pb-10 font-[family-name:var(--font-geist-sans)] bg-slate-500/10 overflow-y-auto">
          <header className="text-center">
            <h1 className="text-3xl font-bold">Next.js Movie App</h1>
            <p className="text-gray-600 mt-2">
              A simple movie browsing application built with Next.js
            </p>
          </header>
          <main className="p-8 gap-16 sm:p-20">{children}</main>
          <footer className="text-center text-sm text-gray-500">
            <p>
              Made with{" "}
              <span role="img" aria-label="heart">
                ❤️
              </span>{" "}
              by <a href="">Webking</a>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
